url: ''
baseurl: ''
title: LHJ
description: coding blog
avatar: ''
favicon: ''
language: ko
icons:
  rss: true
  email: null
  github: ''
  bitbucket: null
  twitter: ''
  facebook: null
  google_plus: null
  tumblr: null
  behance: null
  dribbble: null
  flickr: null
  instagram: null
  linkedin: null
  pinterest: null
  reddit: null
  soundcloud: null
  stack_exchange: null
  steam: null
  wordpress: null
  youtube: null
permalink: pretty
google_analytics: null
disqus: null
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts
recent_posts_num: 10
paginate: 10
paginate_path: 'page/:num'
share_buttons:
  twitter: true
  facebook: false
  hatena: false
ogp:
  image_url: ''
  fb:
    admin: null
    app_id: null
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji
include:
  - _pages
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: <!--more-->
sass:
  sass_dir: _sass
  style: ':compressed'
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
