title: LEE HYUNG JU
description: Jekyll Blog
author: LHJ
github: https://github.com/hyungju-lee/
about: I'm a FE developer.
disqus_shortname: LEE HYUNG JU
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

#social:
#    - icon: fa-facebook
#      link: "#"
#    - icon: fa-twitter
#      link: "#"
#    - icon: fa-linkedin
#      link: "#"
#    - icon: fa-stack-exchange
#      link: "#"
#    - icon: fa-github
#      link: "https://github.com/agusmakmun"

#share:
#  twitter_username: github.io
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: categories
      url: /category/
    - text: My Projects
      url: /projects/

plugins:
  - jekyll-paginate

url: "https://github.com/hyungju-lee/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']